[settings]
animate = true
animation_duration = 0.3
animation_fps = 100.0
default_disable = false
# doesn't work?
hot_reload = true

[modifier_combinations]
regular = "Alt"
super = "Alt + Shift"

[keys]
"regular + Z" = "toggle_space_activated"
"regular + ;" = { move_focus = "left" }
"regular + /" = { move_focus = "down" }
"regular + [" = { move_focus = "up" }
"regular + '" = { move_focus = "right" }
"super + ;" = { move_node = "left" }
"super + /" = { move_node = "down" }
"super + [" = { move_node = "up" }
"super + '" = { move_node = "right" }
"super + Space" = "toggle_window_floating"

[settings.layout]
mode = "master_stack"

[settings.ui.menu_bar]
enabled = true

[settings.layout.gaps.inner]
horizontal = 8.0
vertical = 8.0
