[settings]
animate = true
animation_duration = 0.2
animation_fps = 60.0
default_disable = false
# doesn't work?
hot_reload = true

[modifier_combinations]
regular = "Alt"
super = "Alt + Shift"

[keys]
"regular + Z" = "toggle_space_activated"
"regular + Left" = { move_focus = "left" }
"regular + Down" = { move_focus = "down" }
"regular + Up" = { move_focus = "up" }
"regular + Right" = { move_focus = "right" }
"super + Left" = { move_node = "left" }
"super + Down" = { move_node = "down" }
"super + Up" = { move_node = "up" }
"super + Right" = { move_node = "right" }
"super + Space" = "toggle_window_floating"

[settings.layout]
mode = "bsp"

[settings.ui.menu_bar]
enabled = true

[settings.layout.gaps.inner]
horizontal = 8.0
vertical = 8.0
